.TH SLUGIFY "1" "November 2019" "slugify 4.0.0" "User Commands"
.SH NAME
slugify \- Python slugify application that handles unicode
.SH SYNOPSIS
.B slugify TEXTTOSLUGIFY
.SH DESCRIPTION
slugify is a Python slugifying application that handles unicode. 
.SH EXAMPLES
"slugify This is a test ---" returns "this-is-a-test"
.SH COPYRIGHT
This manual page is Copyright © 2019 Hugo Lefeuvre <hle@debian.org>.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, Version 3 or any later
version published by the Free Software Foundation.
